"""empty message

Revision ID: 90c474e6e7f3
Revises: f8f1956248f8
Create Date: 2022-01-30 17:48:11.644353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c474e6e7f3'
down_revision = 'f8f1956248f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('admission_type', sa.String(length=200), nullable=True))
    op.add_column('programme', sa.Column('programme_duration_direct', sa.String(length=200), nullable=True))
    op.add_column('programme', sa.Column('programme_duration_topup', sa.String(length=200), nullable=True))
    op.drop_column('programme', 'programme_duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programme', sa.Column('programme_duration', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('programme', 'programme_duration_topup')
    op.drop_column('programme', 'programme_duration_direct')
    op.drop_column('agreement', 'admission_type')
    # ### end Alembic commands ###
