"""empty message

Revision ID: f8f1956248f8
Revises: 
Create Date: 2022-01-15 11:42:27.017276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f1956248f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_password'), 'admin', ['password'], unique=False)
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=False)
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('transaction_mode', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('card_type', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coreforgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=True),
    sa.Column('subject_status', sa.String(length=200), nullable=True),
    sa.Column('min_grade', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_name', sa.String(length=200), nullable=False),
    sa.Column('faculty_code', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lengthofgradingsubjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registrar_name', sa.String(length=200), nullable=True),
    sa.Column('registrar_signature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('srcdues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('subject_status', sa.String(length=200), nullable=True),
    sa.Column('min_grade', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicants_full_name', sa.String(length=200), nullable=True),
    sa.Column('applicants_email', sa.String(length=200), nullable=True),
    sa.Column('applicants_contact', sa.String(length=200), nullable=True),
    sa.Column('application_type', sa.String(length=200), nullable=True),
    sa.Column('payment_mode', sa.String(length=200), nullable=True),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('date_bought', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_users',
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('pin', sa.String(length=200), nullable=True),
    sa.Column('buy_id', sa.Integer(), nullable=True),
    sa.Column('date_bought', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['buy_id'], ['buy.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliction_type', sa.String(length=200), nullable=True),
    sa.Column('is_avaliable', sa.Boolean(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('home_town', sa.String(length=200), nullable=True),
    sa.Column('home_region', sa.String(length=200), nullable=True),
    sa.Column('marital_status', sa.String(length=200), nullable=True),
    sa.Column('childrens', sa.Integer(), nullable=True),
    sa.Column('religion', sa.String(length=200), nullable=True),
    sa.Column('sponsorship', sa.String(length=200), nullable=True),
    sa.Column('passport_picture', sa.Text(), nullable=True),
    sa.Column('employed', sa.Boolean(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postgradprogramme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_title', sa.String(length=200), nullable=False),
    sa.Column('programme_duration', sa.String(length=200), nullable=True),
    sa.Column('min_gpa', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('programme_admission_fees', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_name', sa.String(length=200), nullable=False),
    sa.Column('programme_duration', sa.String(length=200), nullable=True),
    sa.Column('cut_off_point', sa.Integer(), nullable=True),
    sa.Column('min_class',sa.String(length=200),nullable=True),
    sa.Column('is_avaliable', sa.Boolean(), nullable=True),
    sa.Column('programme_admission_fees', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=200), nullable=True),
    sa.Column('person_full_name', sa.String(length=200), nullable=False),
    sa.Column('programme_listed', sa.String(length=200), nullable=False),
    sa.Column('admission_status', sa.String(length=200), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['level_id'], ['type.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_choice', sa.String(length=200), nullable=True),
    sa.Column('second_choice', sa.String(length=200), nullable=True),
    sa.Column('third_choice', sa.String(length=200), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('contact_number', sa.String(length=200), nullable=True),
    sa.Column('contact_number_2', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('residence_address', sa.String(length=200), nullable=True),
    sa.Column('digital_address', sa.String(length=200), nullable=True),
    sa.Column('postal_address', sa.String(length=200), nullable=True),
    sa.Column('post_town', sa.String(length=200), nullable=True),
    sa.Column('post_region', sa.String(length=200), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programme.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], )
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('date_started', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('offered_programme', sa.String(length=200), nullable=True),
    sa.Column('education_type', sa.String(length=200), nullable=True),
    sa.Column('graduated_class', sa.String(length=200), nullable=True),
    sa.Column('graduated_gpa', sa.String(length=10), nullable=True),
    sa.Column('certificate_file', sa.String(length=200), nullable=True),
    sa.Column('transcript_file', sa.String(length=200), nullable=True),
    sa.Column('second_graduated_class', sa.String(length=200), nullable=True),
    sa.Column('second_graduated_gpa', sa.String(length=200), nullable=True),
    sa.Column('second_certificate_file', sa.String(length=200), nullable=True),
    sa.Column('second_transcript_file', sa.String(length=200), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_name', sa.String(length=200), nullable=True),
    sa.Column('organisation_address', sa.String(length=200), nullable=True),
    sa.Column('organisation_contact', sa.String(length=200), nullable=True),
    sa.Column('position_held', sa.String(length=200), nullable=True),
    sa.Column('date_started', sa.Date(), nullable=True),
    sa.Column('date_ended', sa.Date(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postgradchoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_choice', sa.String(length=200), nullable=True),
    sa.Column('second_choice', sa.String(length=200), nullable=True),
    sa.Column('third_choice', sa.String(length=200), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referees_name', sa.String(length=200), nullable=True),
    sa.Column('referees_work_place', sa.String(length=200), nullable=True),
    sa.Column('referees_address', sa.String(length=200), nullable=True),
    sa.Column('referees_email', sa.String(length=200), nullable=True),
    sa.Column('referees_contact', sa.String(length=200), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert_1_number', sa.String(length=200), nullable=True),
    sa.Column('results_type', sa.String(length=200), nullable=True),
    sa.Column('subject_core_1', sa.String(length=200), nullable=True),
    sa.Column('core_grade_1', sa.String(length=200), nullable=True),
    sa.Column('subject_core_2', sa.String(length=200), nullable=True),
    sa.Column('core_grade_2', sa.String(length=200), nullable=True),
    sa.Column('subject_core_3', sa.String(length=200), nullable=True),
    sa.Column('core_grade_3', sa.String(length=200), nullable=True),
    sa.Column('subject_core_4', sa.String(length=200), nullable=True),
    sa.Column('core_grade_4', sa.String(length=200), nullable=True),
    sa.Column('subject_elective_1', sa.String(length=200), nullable=True),
    sa.Column('elective_grade_1', sa.String(length=200), nullable=True),
    sa.Column('subject_elective_2', sa.String(length=200), nullable=True),
    sa.Column('elective_grade_2', sa.String(length=200), nullable=True),
    sa.Column('subject_elective_3', sa.String(length=200), nullable=True),
    sa.Column('elective_grade_3', sa.String(length=200), nullable=True),
    sa.Column('subject_elective_4', sa.String(length=200), nullable=True),
    sa.Column('elective_grade_4', sa.String(length=200), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('referees')
    op.drop_table('postgradchoice')
    op.drop_table('employment')
    op.drop_table('education')
    op.drop_table('courses')
    op.drop_table('contact')
    op.drop_table('choice')
    op.drop_table('agreement')
    op.drop_table('admission')
    op.drop_table('programme')
    op.drop_table('postgradprogramme')
    op.drop_table('applicant')
    op.drop_table('type')
    op.drop_table('card')
    op.drop_table('role_users')
    op.drop_table('department')
    op.drop_table('buy')
    op.drop_table('subject')
    op.drop_table('srcdues')
    op.drop_table('role')
    op.drop_table('registrar')
    op.drop_table('lengthofgradingsubjects')
    op.drop_table('faculty')
    op.drop_table('coreforgrades')
    op.drop_table('cardstate')
    op.drop_table('bank')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_index(op.f('ix_admin_password'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
